version: '3.8'

services:
  zoom-discord-webhook:
    image: diogotcorreia/zoom-discord-webhook:v1.0.0
    volumes:
      - type: bind
        source: ./data
        target: /app/data
    restart: unless-stopped
